version: '1.0'

service:
  db:
    image: postgres:10.5
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'
  
  client:
    container_name: react_app
    build: